apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "sample-fastapi-app.fullname" . }}

spec:
  selector:
    matchLabels:
      app: python-sample-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: python-sample-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          # enter the path to your image, be sure to include the correct region prefix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}