apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-fastapi-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: python-sample-app